MyFirstSite/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyFirstSite.DomainModels;
using MyFirstSite.Helpers;
using MyFirstSite.Helpers.LocalDB;
using MyFirstSite.Mappers;
using MyFirstSite.Models;
using System.Net;
using System.Xml.Linq;

namespace MyFirstSite.Controllers
{
    public class BookController : Controller
    {
        public IActionResult Index()
        {
            var books = BookDb.Books.Select(x => x.ToViewModel()).OrderBy(x => x.Category.Name).ThenBy(x => x.Title).ToList();
            return View(books);
        }

        public IActionResult Details(int id)
        {
            var book = BookDb.Books.FirstOrDefault(x => x.Id == id);

            if(book == null)
            {
                throw new Exception($"Book with ID: {id} not found!");
            }

            return View(book.ToViewModel());
        }

        /*
        public IActionResult Sort(string selectOption)
        {
            var book = BookDb.Books.Select(x => x.ToViewModel());
            //var book = BookDb.Books.Select(x => x.Category.Name.ToLower() == selectOption.ToLower());
            //var book = BookDb.Books.FirstOrDefault(x => x.Category.Name == selectOption);

            if (selectOption == null) 
            {
                throw new Exception("No category selected");
            }

            while (selectOption != null)
            { 
                book = book.Where(a => a.Category.Name.ToLower().Equals(selectOption.ToLower()));
                break;
            }

            return View(book.ToList());
        }*/

        public IActionResult Sort(int? id)
        {
            var categoryItem = new BookCategorySortModel();

            if (id.HasValue)
            {
                var item = BookDb.Categories.FirstOrDefault(x => x.Id == id);

                if (id == null)
                {
                    throw new Exception($"Menu item with Id {id} does not exist");
                }

                categoryItem = new BookCategorySortModel
                {
                    Id = item.Id,

                };
            }

            ViewBag.Categories = BookDb.Categories.Select(x => new SelectListItem(x.Name, x.Id.ToString())).ToList();

            return View(categoryItem);
        }

        [HttpPost]
        public IActionResult SortCategory(BookCategorySortModel model)
        {
            var matchingCategory = BookDb.Categories.FirstOrDefault(x => x.Id == model.Id);
            if(matchingCategory == null)
            {
                throw new Exception("Category not selected");
            }

            return RedirectToAction("Index");
        }

        public IActionResult CreateEditBook(int? id)
        {
            var model = new BookModel();

            if (id.HasValue)
            {
                var domainModel = BookDb.Books.FirstOrDefault(x => x.Id == id.Value);

                if(domainModel == null) 
                {
                    throw new Exception("Book with that ID does not exist.");
                }
                model = domainModel.ToViewModel();
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Save(BookModel book)
        {
            if(string.IsNullOrEmpty(book.Title) 
                || string.IsNullOrEmpty(book.Author)
                || string.IsNullOrEmpty(book.Description))
            {
                throw new Exception("Please fill out all the properties");
            }

            if(BookDb.Books.Any(x => x.Title.ToLower() == book.Title.ToLower() && x.Id != book.Id))
            {
                throw new Exception($"Book with the name {book.Title} already exists");
            }

            if(book.Id == 0)
            {
                var model = new Book(IdHelper.GetRandomId(), book.Title, book.Author, book.Description);
                BookDb.Books.Add(model);
                return RedirectToAction("Index");
            }

            var existingBook = BookDb.Books.FirstOrDefault(x => x.Id == book.Id);
            if(existingBook == null) 
            {
                throw new Exception($"Book with {book.Id} does not exist");
            }

            BookDb.Books.Remove(existingBook);
            existingBook.Title = book.Title;
            existingBook.Author = book.Author;
            existingBook.Description = book.Description;
            BookDb.Books.Add(existingBook);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var existingBook = BookDb.Books.FirstOrDefault(x => x.Id == id);
            if(existingBook == null)
            {
                throw new Exception($"Book with Id {id} does not exist");
            }

            BookDb.Books.Remove(existingBook);

            return RedirectToAction("Index");
        }
    }
}

MyFirstSite/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyFirstSite.DomainModels;
using MyFirstSite.Helpers;
using MyFirstSite.Helpers.Enums;
using MyFirstSite.Helpers.LocalDB;
using MyFirstSite.Mappers;
using MyFirstSite.Models;

namespace MyFirstSite.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            var category = BookDb.Categories.Select(x => x.ToViewModel()).OrderBy(x => x.Name).ToList();
            return View(category);
        }

        public IActionResult Details(int id)
        {
            var category = BookDb.Categories.FirstOrDefault(x => x.Id == id);

            if(category == null)
            {
                throw new Exception($"Category with Id {id} not found");
            }
            return View(category.ToViewModel());
        }

        public IActionResult CreateEditCategory(int? id) 
        {
            var model = new CategoryModel();

            if (id.HasValue)
            {
                var domainModel = BookDb.Categories.FirstOrDefault(x => x.Id == id.Value);

                if (domainModel == null)
                {
                    throw new Exception($"Category with Id {id} does not exist");
                }

                model = domainModel.ToViewModel(); 
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Save(CategoryModel model) 
        {
            if(string.IsNullOrEmpty(model.Name))
            {
                throw new Exception("All propeties are required");
            }

            if(BookDb.Categories.Any(x => x.Name.ToLower() == model.Name.ToLower() && x.Id != model.Id))
            {
                throw new Exception($"Category with the name {model.Name} already exists");
            }

            if(model.Id == 0)
            {
                var category = new Category(IdHelper.GetRandomId(), model.Name);
                BookDb.Categories.Add(category);
                return RedirectToAction("Index");
            }

            var existingCategory = BookDb.Categories.FirstOrDefault(x => x.Id == model.Id);
            if (existingCategory == null)
            {
                throw new Exception($"Category with Id {model.Id} does not exist");
            }
            BookDb.Categories.Remove(existingCategory);
            existingCategory.Name = model.Name;
            BookDb.Categories.Add(existingCategory);

            return RedirectToAction("Index"); 
        }

        public IActionResult Delete(int id)
        {
            var existingCategory = BookDb.Categories.FirstOrDefault( x => x.Id == id);
            if (existingCategory == null) 
            {
                throw new Exception($"Category with Id {id} does not exist");
            }

            var bookCategory = BookDb.Books.Where(x => x.Category.Id == id).ToList();
            foreach(var bookCat in bookCategory)
            {
                BookDb.Books.Remove(bookCat);
            }

            BookDb.Categories.Remove(existingCategory);

            return RedirectToAction("Index");
        }
    }
}

MyFirstSite/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyFirstSite.DomainModels;
using MyFirstSite.Helpers;
using MyFirstSite.Helpers.LocalDB;
using MyFirstSite.Mappers;
using MyFirstSite.Models;
using System.Diagnostics;
using System.Net.WebSockets;

namespace MyFirstSite.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Index()
        {
            var menu = BookDb.MenuItems.Select(x => x.ToViewModel()).OrderBy(x => x.Book.Title).ThenBy(x => x.Book.Author).ToList();
            return View(menu);
        }

        public IActionResult CreateEditMenuItem(int? id)
        {
            var menuItem = new MenuItemCreateEditModel();

            if(id.HasValue)
            {
                var item = BookDb.MenuItems.FirstOrDefault(x => x.Id == id);

                if (item == null)
                {
                    throw new Exception($"Menu item with Id {item} does not exist");
                }

                menuItem = new MenuItemCreateEditModel
                {
                    Id = item.Id,
                    SelectedBookId = item.Book.Id,
                    Price = item.Price
                };
            }

            ViewBag.Books = BookDb.Books.Select(x => new SelectListItem(x.Title, x.Id.ToString())).ToList();

            return View(menuItem);
        }

        [HttpPost]
        public IActionResult Save(MenuItemCreateEditModel model)
        {
            if(model.SelectedBookId == 0
                || model.Price == 0)
            {
                throw new Exception("All properties required");
            }

            var selectedBook = BookDb.Books.FirstOrDefault(x => x.Id == model.SelectedBookId);
            if(selectedBook == null)
            {
                throw new Exception("Selected book does not exist");
            }

            if(model.Price <= 0 )
            {
                throw new Exception("Book price should be larger than 0");
            }

            if(BookDb.MenuItems.Any(x => x.Id != model.Id 
                                    && x.Book.Id == model.SelectedBookId))
            {
                throw new Exception($"This menu item already exists");
            }

            if(model.Id == 0)
            {
                var menuItem = new MenuItem(IdHelper.GetRandomId(), selectedBook, model.Price);
                BookDb.MenuItems.Add(menuItem);
                return RedirectToAction("Index");
            }

            var existingMenuItem = BookDb.MenuItems.FirstOrDefault(x => x.Id == model.Id);
            if(existingMenuItem == null)
            {
                throw new Exception("Menu item does not exist");
            }
            BookDb.MenuItems.Remove(existingMenuItem);
            existingMenuItem.Book = selectedBook;
            existingMenuItem.Price = model.Price;
            BookDb.MenuItems.Add(existingMenuItem);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var existingMenuItem = BookDb.MenuItems.FirstOrDefault(x => x.Id == id);

            if(existingMenuItem == null)
            {
                throw new Exception($"Menu item with Id {id} does not exist");
            }

            BookDb.MenuItems.Remove(existingMenuItem);

            return RedirectToAction("Index");
        }
    }
}

MyFirstSite/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstSite.DomainModels;
using MyFirstSite.Helpers;
using MyFirstSite.Helpers.LocalDB;
using MyFirstSite.Mappers;
using MyFirstSite.Models;

namespace MyFirstSite.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            var orders = BookDb.Orders.Select(x => x.ToViewModel()).ToList();
            return View(orders);
        }

        public IActionResult CreateOrder()
        {
            return View(new OrderModel());
        }

        public IActionResult Details(int id)
        {
            var order = BookDb.Orders.FirstOrDefault(x => x.Id == id);

            if (order == null)
            {
                throw new Exception($"Order with Id {id} not found");
            }

            return View(order.ToViewModel());
        }

        [HttpPost]
        public IActionResult Save(OrderModel model)
        {
            var order = new Order(IdHelper.GetRandomId(), model.Address, model.PhoneNumber, model.Note, new List<OrderItem>());
            BookDb.Orders.Add(order);

            return RedirectToAction("Details", new { id = order.Id});
        }

        public IActionResult Delete(int id) 
        {
            var existingOrder = BookDb.Orders.FirstOrDefault(x => x.Id == id);
            if(existingOrder != null)
            {
                throw new Exception($"Order with Id {id} does not exist");
            }
            BookDb.Orders.Remove(existingOrder);

            return RedirectToAction("Index");
        }
    }
}

MyFirstSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFirstSite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFirstSite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <!--
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Category
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-action="Sort" asp-controller="Book">Crime</a>
                                <a class="dropdown-item" asp-action="Sort" asp-controller="Book">Fantasy</a>
                                <a class="dropdown-item" asp-action="Sort" asp-controller="Book">Classics</a>
                                <a class="dropdown-item" asp-action="Sort" asp-controller="Book">Horror</a>
                                <a class="dropdown-item" asp-action="Sort" asp-controller="Book">Adventure</a>
                                <a class="dropdown-item" asp-action="Sort" asp-controller="Book">Bestseller</a>
                                <a class="dropdown-item" asp-action="Sort" asp-controller="Book">Other</a>
                            </div>
                        </li>
                        -->
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Sort">Sort by Category</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyFirstSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>