MyFirstSite/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstSite.DomainModels;
using MyFirstSite.Helpers;
using MyFirstSite.Helpers.LocalDB;
using MyFirstSite.Mappers;
using MyFirstSite.Models;

namespace MyFirstSite.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            var orders = BookDb.Orders.Select(x => x.ToViewModel()).ToList();
            return View(orders);
        }

        public IActionResult CreateOrder()
        {
            return View(new OrderModel());
        }

        public IActionResult Details(int id)
        {
            var order = BookDb.Orders.FirstOrDefault(x => x.Id == id);

            if (order == null)
            {
                throw new Exception($"Order with Id {id} not found");
            }

            return View(order.ToViewModel());
        }

        [HttpPost]
        public IActionResult Save(OrderModel model)
        {
            var order = new Order(IdHelper.GetRandomId(), model.Address, model.PhoneNumber, model.Note, new List<OrderItem>());
            BookDb.Orders.Add(order);

            return RedirectToAction("Details", new { id = order.Id});
        }

        public IActionResult Delete(int id) 
        {
            var existingOrder = BookDb.Orders.FirstOrDefault(x => x.Id == id);
            if(existingOrder != null)
            {
                throw new Exception($"Order with Id {id} does not exist");
            }
            BookDb.Orders.Remove(existingOrder);

            return RedirectToAction("Index");
        }
    }
}

MyFirstSite/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyFirstSite.DomainModels;
using MyFirstSite.Helpers;
using MyFirstSite.Helpers.LocalDB;
using MyFirstSite.Models;

namespace MyFirstSite.Controllers
{
    public class OrderItemController : Controller
    {
        public IActionResult CreateOrderItem(int id)
        {
            ViewBag.MenuItems = BookDb.MenuItems.Select(x => new SelectListItem(x.ToString(), x.Id.ToString()));

            var orderItem = new OrderItemModel()
            {
                OrderId = id
            };

            return View(orderItem);
        }

        [HttpPost]
        public IActionResult Save(OrderItemModel model)
        {
            var order = BookDb.Orders.FirstOrDefault(x => x.Id == model.OrderId);
            if (order == null)
            {
                throw new Exception("Order does not exist");
            }

            var menuItem = BookDb.MenuItems.FirstOrDefault(x => x.Id == model.MenuItem.Id);
            if (menuItem == null)
            {
                throw new Exception("Menu item does not exist");
            }

            if (model.Quantity <= 0)
            {
                throw new Exception("Quantity must be greater than 0");
            }

            var orderItem = new OrderItem(IdHelper.GetRandomId(), menuItem, model.Quantity);
            order.OrderItems.Add(orderItem);

            return RedirectToAction("Details", "Order",new {id = model.OrderId});
        }

        public IActionResult Delete(int id)
        {
            var existingOrder = BookDb.Orders.FirstOrDefault(x => x.OrderItems.Any(y => y.Id == id));
            if (existingOrder == null) 
            {
                throw new Exception($"Order that contains order item with Id {id} does not exist");
            }

            var existingOrderItem = existingOrder.OrderItems.First(x => x.Id == id);

            existingOrder.OrderItems.Remove(existingOrderItem);

            return RedirectToAction("Details", "Order", new { id = existingOrder.Id });
        }
    }
}

MyFirstSite/Views/Order/CreateOrder.cshtml
@model OrderModel

<form method="post" asp-action="Save">
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control"/>
    </div>

    <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Note"></label>
        <input asp-for="Note" class="form-control" />
    </div>

    <hr />
    <input type="submit" class="btn btn-secondary" value="Save"/>
</form>

MyFirstSite/Views/Order/Details.cshtml
@using System.Globalization;
@model OrderModel

<div>
    <span class="col-11">
        <h3>@Model.Address</h3>
        <h6>@Model.PhoneNumber</h6>
        <p>@Model.Note</p>
        <h4>@Model.TotalPrice.ToString("C", CultureInfo.CreateSpecificCulture("fr-FR"))</h4>
    </span>
</div>

<a asp-action="CreateOrderItem" asp-controller="OrderItem" asp-route-id="Model.Id" class="btn btn-secondary">Add new item</a>
<table class="table table-stripped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Book</th>
            <th scope="col">Quantity</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for(var i = 0; i < Model.OrderItems.Count; i++)
        {
            <tr>
                <th scope="row">@(i + 1)</th>
                <td>@Model.OrderItems[i].MenuItem.ToString()</td>
                <td>@Model.OrderItems[i].Quantity</td>
                <td>
                    <a asp-action="Delete" asp-route-id="OrderItem" class="btn btn-primary">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MyFirstSite/Views/Order/Index.cshtml
@using System.Globalization;
@model List<OrderModel>

<a asp-action="CreateOrder" class="btn btn-secondary">Add new</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Address</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Note</th>
            <th scope="col">Items</th>
            <th scope="col">Total Price</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for(var i = 0; i < Model.Count; i++)
        {
            <tr>
                <th scope="row">@(i + 1)</th>
                <td>@Model[i].Address</td>
                <td>@Model[i].PhoneNumber</td>
                <td>@Model[i].Note</td>
                <td>
                    <ul>
                        @foreach(var item in Model[i].OrderItems)
                        {
                            <li>@item.MenuItem.ToString() x @item.Quantity</li>
                        }
                    </ul>
                </td>
                <td>@Model[i].TotalPrice.ToString("C", CultureInfo.CreateSpecificCulture("fr-FR"))</td>
                <td>
                    <a asp-action="Details" asp-route-id="@Model[i].Id" class="btn btn-primary">Details</a>
                    <a asp-action="Delete" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>